name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  http: ^1.1.0
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  search_app_bar_page: ^2.1.5
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


#  assets:
#       - images/a_dot_burr.jpeg
#       - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
         - asset: assets/fonts/Rubik/Rubik-Black.ttf
           weight: 600
         - asset: assets/fonts/Rubik/Rubik-Bold.ttf
           weight: 500
         - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
           weight: 400
         - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
           weight: 300
         - asset: assets/fonts/Rubik/Rubik-Light.ttf
           weight: 200
         - asset: assets/fonts/Rubik/Medium.ttf
           weight: 100
         - asset: assets/fonts/Rubik/Regular.ttf
           weight: 100
           style: normal

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
